### ISSUE TITLE
"incorrect path" Error when using a repo with subgroups.

### ISSUE THREAD

**Issue by apintocr** [clns/gitlab-cli#10]
When accessing a repo within a sub group, for example:

`https://gitlab.com/maingroup/subgroup/project`

The following error is returned:
````
error: invalid target repository: failed to get GitLab project https://gitlab.com/maingroup/subgroup/project': incorrect path: maingroup/subgroup/project
````

**Comment by gerbsen** [comment]
Same here :(

**Comment by gerbsen** [comment]
I would pretty much like to fix this, but I do not have any knowledge of `go`, any hints?

**Comment by clns** [comment]
I'll try to work on this today.

**Comment by clns** [comment]
This has been fixed in 0.3.2. Update by running:

```sh
gitlab-cli update
```

**Comment by gerbsen** [comment]
Thank you! The update command is not working for me, but I installed it via the regular [instructions](https://github.com/clns/gitlab-cli/releases/tag/0.3.2) with no problems! 

```gerb@macbook ~/D/a/gitlab-cli (master) [2]> gitlab-cli update
error: failed to retrieve the latest release Get https://api.github.com/repos/clns/gitlab-cli/releases/latest: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)```

**Comment by clns** [comment]
Yes, I've seen this error as well, however it worked the second time.
