### ISSUE TITLE
Do you have a plan to make a feature that managing `Protected Branches`?

### ISSUE THREAD

**Issue by luckymagic7** [clns/gitlab-cli#16]
Hi, I want to control a permission to push to some repository.

I think there is no feature that can manage repository.

I mean, I want to do like below:

`https://docs.gitlab.com/ee/user/project/protected_branches.html`

using `gitlab-cli`.

Many Thanks!

**Comment by clns** [comment]
I don't have time right now to work on this. If you want, feel free to submit a pull request and I can merge it.
