### ISSUE TITLE
error on use

### ISSUE THREAD

**Issue by llwp** [clns/gitlab-cli#2]
every use generates the same:
`error: open : no such file or directory`
- run as typical user
- run as priv user
- run as root

...same result

**Comment by clns** [comment]
Not sure why you get this, I've never seen or encountered something similar, and I can't really help with so little info.

**Comment by Routhinator** [comment]
Got this today, solution is to create an empty config file. In Linux:

`touch ~/.gitlab-cli.yml`

There seems to be a bug where the tool doesn't know what to do if a file doesn't already exist and it errors out.
