### ISSUE TITLE
Install with go get instructions

### ISSUE THREAD

**Issue by kifirkin** [clns/gitlab-cli#7]
Can I install `gitlab-cli` with `go get` command?

**Comment by clns** [comment]
Yes you can install it with `go get github.com/clns/gitlab-cli`, however this also downloads the source code (which you may not be interested in) and it does not download any dependencies stored in the vendor directory. This can cause the build to fail if you have outdated or different dependency package versions.

My recommendation is to only download the pre-compiled binary, [per the instructions](https://github.com/clns/gitlab-cli/releases).

**Comment by kifirkin** [comment]
Ok, thanks for the response!

By the way does `go get ./...` or `go get all` pull needed dependancies?

**Comment by clns** [comment]
Yes, `go get` downloads any missing dependencies, but the vendor directory makes sure you're using the supported versions of those dependencies.

**Comment by kifirkin** [comment]
Oh I see, thanks!
